/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import homePages from "./scenePages/homePages"

export default class GameConfig {
    static init() {
        //注册Script或者Runtime引用
        let reg = Laya.ClassUtils.regClass;
		reg("scenePages/homePages.js",homePages);
    }
}
GameConfig.width = 750;
GameConfig.height = 1624;
GameConfig.scaleMode ="fixedwidth";
GameConfig.screenMode = "vertical";
GameConfig.alignV = "top";
GameConfig.alignH = "left";
GameConfig.startScene = "scenePages/homePage.scene";
GameConfig.sceneRoot = "";
GameConfig.debug = false;
GameConfig.stat = false;
GameConfig.physicsDebug = true;
GameConfig.exportSceneToJson = true;

GameConfig.init();
